name: 'Cloud Run Deploy'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  serviceName:
    description: 'Name of image to push'
    required: true
  gcloudProjectId:
    description: 'Google Cloud project ID'
    required: true
