name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint Client
      uses: georgemblack/actions/yarn-command@1.0.4
      with:
        command: lint
    - name: Cloud Run Deploy
      uses: georgemblack/actions/cloud-run-deploy@1.0.13
      with:
        serviceName: web-api
        projectId: ${{ secrets.GCLOUD_PROJECT_ID }}
        runtimeServiceAccount: ${{ secrets.GCLOUD_RUNTIME_SERVICE_ACCOUNT }}
        cloudBuildBucket: cloudbuild.georgeblack.me
        region: us-east1
        concurrency: 25
        maxInstances: 1
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
